### ISSUE TITLE
Suggestion: CLI upload

### ISSUE THREAD

**Issue by florian-berger** [PlasmoHQ/edge-addons-api#49]
it would be great to have the possibility to execute the Edge publishing via CLI command. Maybe get inspired by [chrome-webstore-upload-cli](https://github.com/fregante/chrome-webstore-upload-cli).

**Comment by louisgv** [comment]
Thanks for the suggestion! - ATM, these packages were meant to be used via the github action bpp: https://github.com/PlasmoHQ/bpp

I do plan to add it into the plasmo framework (https://github.com/PlasmoHQ/plasmo) eventually (as a submit cmd). Haven't got time to get it done tho xD...
